# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: build action

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.UBUNTU_SERVER_IP }}
        username: ${{ secrets.UBUNTU_SERVER_USERNAME }}
        password: ${{ secrets.UBUNTU_SERVER_PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          rm -rf /dev/project/kafka-demo
          cp /home/runner/work/kafka_demo/kafka_demo/target/*.jar /dev/project/kafka-demo
